/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameMode = { 'vsAI' : null } |
  { 'multiplayer' : null };
export interface GameState {
  'moves' : Array<Move>,
  'mode' : GameMode,
  'gameStatus' : GameStatus,
  'player1' : Principal,
  'player2' : [] | [Principal],
  'turnWhite' : boolean,
  'board' : Array<Array<[] | [Piece]>>,
}
export type GameStatus = { 'stalemate' : null } |
  { 'draw' : null } |
  { 'playing' : null } |
  { 'checkmate' : null } |
  { 'waiting' : null };
export interface Move {
  'to' : Position,
  'from' : Position,
  'captured' : [] | [Piece],
  'piece' : Piece,
}
export interface Piece { 'pieceType' : PieceType, 'isWhite' : boolean }
export type PieceType = { 'king' : null } |
  { 'pawn' : null } |
  { 'rook' : null } |
  { 'queen' : null } |
  { 'knight' : null } |
  { 'bishop' : null };
export interface Position { 'file' : bigint, 'rank' : bigint }
export type Principal = Principal;
export interface _SERVICE {
  'createRoom' : ActorMethod<[GameMode], string>,
  'getGameState' : ActorMethod<[string], [] | [GameState]>,
  'joinRoom' : ActorMethod<[string], boolean>,
  'makeMove' : ActorMethod<[string, Position, Position], boolean>,
  'resetGame' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];