/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CamSession {
    mobileCandidates: Array<string>;
    offer: string;
    desktopCandidates: Array<string>;
    answer?: string;
}
export interface Move {
    to: Position;
    from: Position;
    captured?: Piece;
    piece: Piece;
}
export interface Position {
    file: bigint;
    rank: bigint;
}
export type Principal = Principal;
export interface Piece {
    pieceType: PieceType;
    isWhite: boolean;
}
export interface GameState {
    moves: Array<Move>;
    mode: GameMode;
    gameStatus: GameStatus;
    player1: Principal;
    player2?: Principal;
    turnWhite: boolean;
    board: Array<Array<Piece | null>>;
}
export enum GameMode {
    vsAI = "vsAI",
    multiplayer = "multiplayer"
}
export enum GameStatus {
    stalemate = "stalemate",
    draw = "draw",
    playing = "playing",
    checkmate = "checkmate",
    waiting = "waiting"
}
export enum PieceType {
    king = "king",
    pawn = "pawn",
    rook = "rook",
    queen = "queen",
    knight = "knight",
    bishop = "bishop"
}
export interface backendInterface {
    addCamIceCandidate(sessionId: string, candidate: string, fromMobile: boolean): Promise<boolean>;
    createCamSession(offer: string): Promise<string>;
    createRoom(mode: GameMode): Promise<string>;
    getCamSession(sessionId: string): Promise<CamSession | null>;
    getGameState(roomCode: string): Promise<GameState | null>;
    joinRoom(roomCode: string): Promise<boolean>;
    makeMove(roomCode: string, from: Position, to: Position): Promise<boolean>;
    resetGame(roomCode: string): Promise<boolean>;
    setCamAnswer(sessionId: string, answer: string): Promise<boolean>;
}
import type { CamSession as _CamSession, GameMode as _GameMode, GameState as _GameState, GameStatus as _GameStatus, Move as _Move, Piece as _Piece, PieceType as _PieceType, Position as _Position, Principal as _Principal } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCamIceCandidate(arg0: string, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCamIceCandidate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCamIceCandidate(arg0, arg1, arg2);
            return result;
        }
    }
    async createCamSession(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCamSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCamSession(arg0);
            return result;
        }
    }
    async createRoom(arg0: GameMode): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(to_candid_GameMode_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(to_candid_GameMode_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCamSession(arg0: string): Promise<CamSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCamSession(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCamSession(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameState(arg0: string): Promise<GameState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRoom(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0);
            return result;
        }
    }
    async makeMove(arg0: string, arg1: Position, arg2: Position): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.makeMove(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeMove(arg0, arg1, arg2);
            return result;
        }
    }
    async resetGame(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetGame(arg0);
            return result;
        }
    }
    async setCamAnswer(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setCamAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCamAnswer(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CamSession_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CamSession): CamSession {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Move_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Move): Move {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PieceType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PieceType): PieceType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Piece_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Piece): Piece {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Piece]): Piece | null {
    return value.length === 0 ? null : from_candid_Piece_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CamSession]): CamSession | null {
    return value.length === 0 ? null : from_candid_CamSession_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameState]): GameState | null {
    return value.length === 0 ? null : from_candid_GameState_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: _Position;
    from: _Position;
    captured: [] | [_Piece];
    piece: _Piece;
}): {
    to: Position;
    from: Position;
    captured?: Piece;
    piece: Piece;
} {
    return {
        to: value.to,
        from: value.from,
        captured: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.captured)),
        piece: from_candid_Piece_n14(_uploadFile, _downloadFile, value.piece)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pieceType: _PieceType;
    isWhite: boolean;
}): {
    pieceType: PieceType;
    isWhite: boolean;
} {
    return {
        pieceType: from_candid_PieceType_n16(_uploadFile, _downloadFile, value.pieceType),
        isWhite: value.isWhite
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mobileCandidates: Array<string>;
    offer: string;
    desktopCandidates: Array<string>;
    answer: [] | [string];
}): {
    mobileCandidates: Array<string>;
    offer: string;
    desktopCandidates: Array<string>;
    answer?: string;
} {
    return {
        mobileCandidates: value.mobileCandidates,
        offer: value.offer,
        desktopCandidates: value.desktopCandidates,
        answer: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.answer))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moves: Array<_Move>;
    mode: _GameMode;
    gameStatus: _GameStatus;
    player1: _Principal;
    player2: [] | [_Principal];
    turnWhite: boolean;
    board: Array<Array<[] | [_Piece]>>;
}): {
    moves: Array<Move>;
    mode: GameMode;
    gameStatus: GameStatus;
    player1: Principal;
    player2?: Principal;
    turnWhite: boolean;
    board: Array<Array<Piece | null>>;
} {
    return {
        moves: from_candid_vec_n10(_uploadFile, _downloadFile, value.moves),
        mode: from_candid_GameMode_n18(_uploadFile, _downloadFile, value.mode),
        gameStatus: from_candid_GameStatus_n20(_uploadFile, _downloadFile, value.gameStatus),
        player1: value.player1,
        player2: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.player2)),
        turnWhite: value.turnWhite,
        board: from_candid_vec_n23(_uploadFile, _downloadFile, value.board)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    king: null;
} | {
    pawn: null;
} | {
    rook: null;
} | {
    queen: null;
} | {
    knight: null;
} | {
    bishop: null;
}): PieceType {
    return "king" in value ? PieceType.king : "pawn" in value ? PieceType.pawn : "rook" in value ? PieceType.rook : "queen" in value ? PieceType.queen : "knight" in value ? PieceType.knight : "bishop" in value ? PieceType.bishop : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vsAI: null;
} | {
    multiplayer: null;
}): GameMode {
    return "vsAI" in value ? GameMode.vsAI : "multiplayer" in value ? GameMode.multiplayer : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stalemate: null;
} | {
    draw: null;
} | {
    playing: null;
} | {
    checkmate: null;
} | {
    waiting: null;
}): GameStatus {
    return "stalemate" in value ? GameStatus.stalemate : "draw" in value ? GameStatus.draw : "playing" in value ? GameStatus.playing : "checkmate" in value ? GameStatus.checkmate : "waiting" in value ? GameStatus.waiting : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Move>): Array<Move> {
    return value.map((x)=>from_candid_Move_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<[] | [_Piece]>>): Array<Array<Piece | null>> {
    return value.map((x)=>from_candid_vec_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_Piece]>): Array<Piece | null> {
    return value.map((x)=>from_candid_opt_n13(_uploadFile, _downloadFile, x));
}
function to_candid_GameMode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    vsAI: null;
} | {
    multiplayer: null;
} {
    return value == GameMode.vsAI ? {
        vsAI: null
    } : value == GameMode.multiplayer ? {
        multiplayer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
